### ISSUE TITLE
Multi-Acc-Support.

### ISSUE THREAD

**Issue by Raxana7** [Refloow/Steam-Auto-Friend#1]
Need multi-account-support.

**Comment by Refloow** [comment]
Hi we usually charge for custom feature requests and we fix the issues with the current free features of the software that we provide. We do accept some new feature suggestions (ones from discord server), and this is the one of the things that will be added in the future update. Soon we will update all of the projects to newer versions adding some new features (in this particular project that feature) and more exciting things to other projects including one new project release, if you like our work and want to support it leave star on this repository so other people find it more easily !
